version: "3"
services:
 mqtt:
      image: eclipse-mosquitto:1.6.15-openssl
      networks:
       - mqtt-network
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped

networks:
  mqtt-network:
    driver: bridge